# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aa98a21b27381151ffe8e02200868de2c36cee32ee460db314ac2103976aa21bcb35ee008c54a51604ed32297deb2944ec1c61773e20e9c263a4c6381b4e927

test:
  secret_key_base: e8cd4463cb86aa43fb20dcaaf14a64939b4384da736f587dfe031fa27bd9089198b69de1689f02c8af0eaf8d997b71523afa9c82e99f0c5fbb57b2ef8a920c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
